version: '3.8'

services:
  backend:
    build: path/to/backend/directory
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://prisma:prisma@database:5432/blog'
    depends_on:
      - database

  frontend:
    build: path/to/frontend/directory
    ports:
      - '5173:5173'
    depends_on:
      - backend

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
